site_name: doc-builder Documentation

# mkdocs.yml
site_url: https://thehive-project.github.io/thehive4py
theme:
  name: "material"
  logo: 'images/thehive.png'
  palette:
    primary: 'blue'
    accent: blue

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - awesome-pages

extra_css:
  - custom.css

extra:
  social:
    - icon: fontawesome/solid/house
      link: "https://www.strangebee.com"
    - icon: fontawesome/brands/wordpress
      link: "https://blog.strangebee.com"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/TheHive_Project"
    - icon: fontawesome/brands/github
      link: "https://github.com/TheHive-Project"
    - icon: fontawesome/brands/discord
      link: "https://chat.strangebee.com"
repo_name: "TheHive-Project/TheHive4py"
repo_url: "https://github.com/TheHive-Project/doc-builder"
markdown_extensions:
    - toc:
        permalink: "#"
    - codehilite
    - admonition
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
